name: My-basics-CI-GitActions

on:
  push:
    branches:
      - main

jobs:
  my-testings:
    runs-on: ubuntu-latest
    
    steps:
    - name: Print Hello Message 1
      run: echo "Hello World block bild 1"
  
  my_depoloy:
    runs-on: ubuntu-latest
    needs: [my-testings]
    
    steps:
    - name: Print Hello Message 2
      run: echo "Hello World block bild 2"
